name: stack_overflow_users
description: A Flutter Exam
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  go_router: ^6.5.2
  chopper: ^6.1.1
  chopper_built_value: ^1.2.0
  built_value: ^8.4.4
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  injectable: ^2.1.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  built_value_generator: ^8.4.4
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/