name: stack_overflow_users
description: A Flutter Exam
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.18
  collection: ^1.17.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  go_router: ^6.5.2
  chopper: ^6.1.1
  chopper_built_value: ^1.2.0
  built_value: ^8.4.4
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  injectable: ^2.1.1
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.18
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  loading_animations: ^2.2.0
  flutter_adaptive_scaffold: ^0.1.2
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  built_value_generator: ^8.4.4
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/